export const userConstants = {
    REGISTER_REQUEST: 'USER_REGISTER_REQUEST',
    REGISTER_SUCCESS: 'USER_REGISTER_SUCCESS',
    REGISTER_FAILURE: 'USER_REGISTER_FAILURE',

    LOGIN_REQUEST: 'USER_LOGIN_REQUEST',
    LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
    LOGIN_FAILURE: 'USER_LOGIN_FAILURE',
    
    LOGOUT: 'USER_LOGOUT'  
};

export const todoConstants = {
    CREATE_TODO_REQUEST: 'CREATE_TODO_REQUEST',
    CREATE_TODO_SUCCESS: 'CREATE_TODO_SUCCESS',
    CREATE_TODO_FAILURE: 'CREATE_TODO_FAILURE',

    GET_TODO_REQUEST: 'GET_TODO_REQUEST',
    GET_TODO_SUCCESS: 'GET_TODO_SUCCESS',
    GET_TODO_FAILURE: 'GET_TODO_FAILURE',

    EDIT_TODO_REQUEST: 'EDIT_TODO_REQUEST',
    EDIT_TODO_SUCCESS: 'EDIT_TODO_SUCCESS',
    EDIT_TODO_FAILURE: 'EDIT_TODO_FAILURE',

    UPLOAD_FILE_REQUEST: 'UPLOAD_FILE_REQUEST',
    UPLOAD_FILE_SUCCESS: 'UPLOAD_FILE_SUCCESS',
    UPLOAD_FILE_FAILURE: 'UPLOAD_FILE_FAILURE',

    DELETE_TODO_REQUEST: 'DELETE_TODO_REQUEST',
    DELETE_TODO_SUCCESS: 'DELETE_TODO_SUCCESS',
    DELETE_TODO_FAILURE: 'DELETE_TODO_FAILURE',

    TOGGLE_SHOWARCHIVED: 'TOGGLE_SHOWARCHIVED'
}